project:
  type: website
  output-dir: docs
website:
  title: "Machine Learners Guide to Real World"
  navbar:
    right:
      - about.qmd
      - icon: gpu-card
        href: https://huggingface.co/muhtasham
      - icon: cpu
        href: https://github.com/muhtasham
      - icon: hash
        href: https://twitter.com/muhtasham9
      - icon: file-earmark-person
        href: https://www.linkedin.com/in/muhtasham/
format:
  html:
    theme: cosmo
    css: styles.css



