project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!AGENTS.md"
  resources:
    - robots.txt
    - llms.txt
website:
  title: "Machine Learners Guide to Real World"
  site-url: "https://muhtasham.github.io/blog"
  twitter-card:
    card-style: summary
    creator: muhtasham9
  navbar:
    right:
      - about.qmd
      - icon: gpu-card
        href: https://huggingface.co/muhtasham
      - icon: cpu
        href: https://github.com/muhtasham
      - icon: hash
        href: https://twitter.com/muhtasham9
      - icon: file-earmark-person
        href: https://www.linkedin.com/in/muhtasham/
format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header: header-snippet.html


