project:
  type: website
  output-dir: docs
website:
  title: "Machine Learners Guide to Real World"
  navbar:
    right:
      - about.qmd
      - icon: twitter
        href: https://twitter.com/muhtasham9
      - icon: linkedin
        href: https://www.linkedin.com/in/muhtasham/
      - icon: github
        href: https://github.com/muhtasham

format:
  html:
    theme: Litera
    css: styles.css



