project:
  type: website
  output-dir: docs
website:
  title: "To Data Science and Beyond: A Machine Learning Odyssey"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/muhtasham
      - icon: twitter
        href: https://twitter.com/muhtasham9
      - icon: linkedin
        href: https://linkedin.com/muhtahsam
format:
  html:
    theme: Litera
    css: styles.css



